name: golangci-lint
on: [pull_request]
jobs:
  reviewdog:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - uses: actions/checkout@v2

      # reviewdog
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -runners=golint,govet
